<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JugadorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("
            INSERT INTO jugadores(nombre, apellido, posicion, edad, club, pais_id) VALUES
            ('Saad ', 'Al-sheeb', 'Portero', 32, 'Al-Sadd SC', 1),
            ('Meshaal ', 'Barsham', 'Portero', 24, 'Al-Sadd SC', 1),
            ('Yousef', 'Hassan', 'Portero', 26, 'Al-Gharafa SC', 1),
            ('Pedro', 'Miguel', 'Defensa', 32, 'Al-Sadd SC', 1),
            ('Musab ', 'Khoder', 'Defensa', 29, 'Al-Sadd SC', 1),
            ('Tarek ', 'Salman', 'Defensa', 24, 'Al-Sadd SC', 1),
            ('Bassam ', 'Al-Rawi', 'Defensa', 24, 'Al-Duhail SC', 1),
            ('Boualem', 'Khoukhi', 'Defensa', 32, 'Al-Sadd SC', 1),
            ('Abdelkarim', 'Hassan', 'Defensa', 29, 'Al-Sadd SC', 1),
            ('Ismaeel', 'Mohammad', 'Defensa', 32, 'Al-Duhail SC', 1),
            ('Homam', 'Ahmed', 'Defensa', 23, 'Al-Gharafa SC', 1),
            ('Jassem', 'Gaber', 'Mediocampista', 20, 'Al-Arabi SC', 1),
            ('Ali ', 'Asad', 'Mediocampista', 29, 'Al-Sadd SC', 1),
            ('Assim', 'Madibo', 'Mediocampista', 26, 'Al-Duhail SC', 1),
            ('Mohammed ', 'Waad', 'Mediocampista', 23, 'Al-Sadd SC', 1),
            ('Salem', 'Al-Hajri', 'Mediocampista', 26, 'Al-Sadd SC', 1),
            ('Mustafa Tarek', 'Mashaal', 'Mediocampista', 21, 'Al-Sadd SC', 1),
            ('Karim', 'Boudiaf', 'Mediocampista', 32, 'Al-Duhail SC', 1),
            ('Abdulaziz', 'Hatem', 'Mediocampista', 32, 'Al-Rayyan SC', 1),
            ('Naif', 'Al-Hadhrami', 'Delantero', 21, 'Al-Rayyan SC', 1),
            ('Ahmed', 'Alaaeldin', 'Delantero', 29, 'Al-Gharafa SC', 1),
            ('Hassan', 'Al-Haidos', 'Delantero', 32, 'Al-Sadd SC', 1),
            ('Akram', 'Afif', 'Delantero', 25, 'Al-Sadd SC', 1),
            ('Almoez', 'Ali', 'Delantero', 26, 'Al-Duhail SC', 1),
            ('Mohammed ', 'Muntari', 'Delantero', 28, 'Al-Duhail SC', 1),
            ('Khalid Muneer', 'Mazeed', 'Delantero', 24, 'Al-Wakrah Sc', 1),
            ('Moisés', 'Ramírez', 'Portero', 22, 'Independiente del Valle', 2),
            ('Alexander', 'Domínguez', 'Portero', 35, 'LDU Quito', 2),
            ('Hernán', 'Galíndez', 'Portero', 35, 'Aucas', 2),
            ('Piero', 'Hincapié', 'Defensa', 20, 'Bayer Leverkusen', 2),
            ('Robert', 'Arboleda', 'Defensa', 31, 'Sao Paulo', 2),
            ('Pervis', 'Estupiñan', 'Defensa', 24, 'Brighton', 2),
            ('Angelo', 'Preciado', 'Defensa', 24, 'KRC Genk (Bélgica)', 2),
            ('Jackson', 'Porozo', 'Defensa', 22, 'Troyes', 2),
            ('Xavier', 'Arreaga', 'Defensa', 28, 'Seattle Sounders', 2),
            ('Diego ', 'Palacios', 'Defensa', 23, 'LAFC (Estados Unidos)', 2),
            ('Felix ', 'Torres', 'Defensa', 25, 'Santos', 2),
            ('William', 'Pacho', 'Defensa', 21, 'Royal Amberes', 2),
            ('Carlos', 'Gruezo', 'Mediocampista', 27, 'Augsburgo', 2),
            ('José ', 'Cifuentes', 'Mediocampista', 23, 'LAFC (Estados Unidos)', 2),
            ('Alan', 'Franco', 'Mediocampista', 24, 'Talleres (Argentina)', 2),
            ('Moisés', 'Caicedo', 'Mediocampista', 21, 'Brighton', 2),
            ('Ángel ', 'Mena', 'Mediocampista', 34, 'León (México)', 2),
            ('Jeremy', 'Sarmiento', 'Mediocampista', 20, 'Brighton', 2),
            ('Jhegson', 'Méndez', 'Mediocampista', 25, 'LAFC (Estados Unidos)', 2),
            ('Ayrton ', 'Preciado', 'Mediocampista', 28, 'Santos', 2),
            ('Gonzalo', 'Plata', 'Mediocampista', 22, 'Valladolid', 2),
            ('Romario', 'Ibarra', 'Mediocampista', 28, 'Pachuca ', 2),
            ('Djorkaeff', 'Reasco', 'Delantero', 23, 'Newell´s', 2),
            ('Kevin', 'Rodríguez', 'Delantero', 22, 'Imbadura', 2),
            ('Michael', 'Estrada', 'Delantero', 26, 'Cruz Azul', 2),
            ('Enner', 'Valencia', 'Delantero', 33, 'Fenerbahce', 2),
            ('Edouard', 'Mendy', 'Portero', 30, 'Chelsea', 3),
            ('Alfred', 'Gomis', 'Portero', 29, 'Rennes', 3),
            ('Seny', 'Dieng', 'Portero', 27, 'Queens Park Rangers', 3),
            ('Kalidou', 'Koulibaly', 'Defensa', 31, 'Chelsea', 3),
            ('Pape Abou', 'Cisse', 'Defensa', 27, 'Olympiacos', 3),
            ('Abdou', 'Diallo', 'Defensa', 26, 'RB Leipzig', 3),
            ('Fodé Ballo', 'Touré', 'Defensa', 25, 'Milan', 3),
            ('Formose', 'Mendy', 'Defensa', 21, 'Amiens', 3),
            ('Ismail', 'Jakobs', 'Defensa', 23, 'Monaco', 3),
            ('Youssouf', 'Sabaly', 'Defensa', 29, 'Betis', 3),
            ('Idrissa Gana', 'Gueye', 'Mediocampista', 33, 'Everton', 3),
            ('Cheikhou', 'Kouyaté', 'Mediocampista', 32, 'Nottingham Forest', 3),
            ('Nampalys', 'Mendy', 'Mediocampista', 30, 'Leicester City', 3),
            ('Pape', 'Gueye', 'Mediocampista', 23, 'Marsella', 3),
            ('Pape Matar', 'Sarr', 'Mediocampista', 20, 'Tottenham', 3),
            ('Mamadou Loum', 'N\'Diaye', 'Mediocampista', 25, 'Reading', 3),
            ('Moustapha', 'Name', 'Mediocampista', 27, 'Pafos (Chipre)', 3),
            ('Pathe', 'Ciss', 'Mediocampista', 28, 'Rayo Vallecano', 3),
            ('Sadio', 'Mané', 'Delantero', 30, 'Bayern Múnich', 3),
            ('Ismalia', 'Sarr', 'Delantero', 24, 'Watford', 3),
            ('Boulaye', 'Dia', 'Delantero', 26, 'Salernitana (Italia)', 3),
            ('Bamba', 'Dieng', 'Delantero', 22, 'Marsella', 3),
            ('Illiam', 'Ndiaye', 'Delantero', 22, 'Sheffield United', 3),
            ('Famara', 'Diedhou', 'Delantero', 29, 'Alanyaspor', 3),
            ('Krepin', 'Diatta', 'Delantero', 23, 'Monaco', 3),
            ('Nicolas', 'Jackson', 'Delantero', 21, 'Villareal', 3),
            ('Justin', 'Bijlow', 'Portero', 24, 'Feyenord', 4),
            ('Remko', 'Pasveer', 'Portero', 39, 'Ajax', 4),
            ('Andries', 'Noppert', 'Portero', 28, 'Heerenveen', 4),
            ('Virgil van', 'Dijk', 'Defensa', 31, 'Liverpool', 4),
            ('Nathan ', 'Aké', 'Defensa', 27, 'Manchester City', 4),
            ('Daley', 'Blind', 'Defensa', 32, 'Ajax', 4),
            ('Jurriën', 'Timber', 'Defensa', 21, 'Ajax', 4),
            ('Denzel', 'Dumfries', 'Defensa', 26, 'Inter', 4),
            ('Mathijs', 'de Ligt', 'Defensa', 23, 'Bayern Múnich', 4),
            ('Tyrell', 'Malacia', 'Defensa', 23, 'Manchester City', 4),
            ('Jeremie', 'Frimpong', 'Defensa', 21, 'Bayer Leverkusen', 4),
            ('Stefan', 'de Vrij', 'Defensa', 30, 'Inter', 4),
            ('Steven ', 'Berghuis', 'Mediocampista', 30, 'Ajax', 4),
            ('Frenkie', 'de Jong', 'Mediocampista', 25, 'FC Barcelona', 4),
            ('Davy', 'Klaassen', 'Mediocampista', 29, 'Ajax', 4),
            ('Teun', 'Koopmeiners', 'Mediocampista', 24, 'Atalanta', 4),
            ('Cody', 'Gakpo', 'Mediocampista', 23, 'PSV', 4),
            ('Marten', 'de Room', 'Mediocampista', 31, 'Atalanta', 4),
            ('Kenneth', 'Taylor', 'Mediocampista', 20, 'Ajax', 4),
            ('Xavi', 'Simons', 'Mediocampista', 19, 'PSV', 4),
            ('Memphis', 'Depay', 'Delantero', 28, 'FC Barcelona', 4),
            ('Steven ', 'Bergwijn', 'Delantero', 25, 'Ajax', 4),
            ('Vicent', 'Janssen', 'Delantero', 28, 'Amberes', 4),
            ('Luuk de', 'Jong', 'Delantero', 32, 'PSV', 4),
            ('Noa', 'Lang', 'Delantero', 23, 'Brujas', 4),
            ('Wout', 'Weghorst', 'Delantero', 30, 'Besiktas', 4),
            ('Jordan', 'Pickford', 'Portero', 28, 'Everton', 5),
            ('Nick', 'Pope', 'Portero', 30, 'Newcastle United', 5),
            ('Aaron', 'Ramsdale', 'Portero', 24, 'Arsenal', 5),
            ('Kyle', 'Walker', 'Defensa', 32, 'Manchester City', 5),
            ('John', 'Stones', 'Defensa', 28, 'Manchester City', 5),
            ('Harry', 'Maguire', 'Defensa', 29, 'Manchester United', 5),
            ('Eric', 'Dier', 'Defensa', 28, 'Tottenham', 5),
            ('Kieran', 'Trippier', 'Defensa', 32, 'Newcastle United', 5),
            ('Luke', 'Shaw', 'Defensa', 27, 'Manchester United', 5),
            ('Trend', 'Alexander-Arnold', 'Defensa', 24, 'Liverpool', 5),
            ('Conor', 'Coady', 'Defensa', 29, 'Everton', 5),
            ('Ben', 'White', 'Defensa', 25, 'Arsenal', 5),
            ('Jordan', 'Henderson', 'Mediocampista', 32, 'Liverpool', 5),
            ('Declan', 'Rice', 'Mediocampista', 23, 'West Ham', 5),
            ('Mason', 'Mount', 'Mediocampista', 23, 'Chelsea ', 5),
            ('Kalvin', 'Phillips', 'Mediocampista', 26, 'Manchester City', 5),
            ('Jude', 'Bellingham', 'Mediocampista', 19, 'Borussia Dortmund', 5),
            ('Conor', 'Gallagher', 'Mediocampista', 22, 'Chelsea ', 5),
            ('James', 'Maddison', 'Delantero', 25, 'Leicester City', 5),
            ('Jack', 'Grealish', 'Delantero', 27, 'Manchester City', 5),
            ('Phil', 'Foden', 'Delantero', 22, 'Manchester City', 5),
            ('Harry', 'Kane', 'Delantero', 29, 'Tottenham', 5),
            ('Raheem', 'Sterling', 'Delantero', 27, 'Chelsea ', 5),
            ('Bukayo', 'Saka', 'Delantero', 21, 'Arsenal', 5),
            ('Callum', 'Wilson', 'Delantero', 30, 'Newcastle United', 5),
            ('Marcus', 'Rashford', 'Delantero', 25, 'Manchester United', 5),
            ('Alireza', 'Beiranvand', 'Portero', 30, 'Persépolis', 6),
            ('Amir', 'Abedzadeh', 'Portero', 29, 'Ponferradina', 6),
            ('Hossein', 'Hosseini', 'Portero', 30, 'Esteghlal', 6),
            ('Payam', 'Niazmand', 'Portero', 27, 'Sepahan', 6),
            ('Majid', 'Hosseini', 'Defensa', 26, 'Kayserispor', 6),
            ('Hossein', 'Kanaani', 'Defensa', 28, 'Al-Ahli SC', 6),
            ('Shoja', 'Khalilzade', 'Defensa', 33, 'Al-Ahli SC', 6),
            ('Morteza', 'Pouraliganji', 'Defensa', 30, 'Persépolis', 6),
            ('Sedegh', 'Moharrami', 'Defensa', 26, 'Dianamo Zagreb', 6),
            ('Milad', 'Mohanmadi', 'Defensa', 29, 'AEK Atenas', 6),
            ('Ehsan', 'Hajsafi', 'Defensa', 32, 'AEK Atenas', 6),
            ('Ramin', 'Razaeian', 'Defensa', 32, 'Sepahan', 6),
            ('Abolfazl', 'Jalali', 'Defensa', 24, 'Esteghlal', 6),
            ('Saeid', 'Ezatolahi', 'Mediocampista', 26, 'Vejle VK', 6),
            ('Ali', 'Karimi', 'Mediocampista', 29, 'Kayserispor', 6),
            ('Ahmad', 'Nourollahi', 'Mediocampista', 29, 'Shabab Dubai', 6),
            ('Rouzbeh', 'Cheshmi', 'Mediocampista', 29, 'Esteghlal', 6),
            ('Saman', 'Ghoddos', 'Mediocampista', 29, 'Brentford', 6),
            ('Vahid', 'Amiri', 'Delantero', 34, 'Persépolis', 6),
            ('Alireza', 'Jahanbakhsh', 'Delantero', 29, 'Feyenord', 6),
            ('Ali', 'Gholizadeh', 'Delantero', 26, 'RSC Charleroi', 6),
            ('Mehdi', 'Torabi', 'Delantero', 28, 'Persépolis', 6),
            ('Sardar', 'Azmoun', 'Delantero', 27, 'Bayer Leverkusen', 6),
            ('Mehdi', 'Taremi', 'Delantero', 30, 'Porto', 6),
            ('Karim', 'Ansarifard', 'Delantero', 32, 'Omonia Nicosia', 6),
            ('Ethan', 'Horvat', 'Portero', 27, 'Luton Town', 7),
            ('Sean', 'Johnson', 'Portero', 33, 'New York City FC', 7),
            ('Matt', 'Turner', 'Portero', 28, 'Arsenal', 7),
            ('Cameron', 'Carter-Vickers', 'Defensa', 24, 'Celtic', 7),
            ('Sergiño', 'Dest', 'Defensa', 22, 'Milan', 7),
            ('Aaron', 'Long', 'Defensa', 30, 'New York Red Bulls', 7),
            ('Shaq', 'Moore', 'Defensa', 26, 'Nashville SC', 7),
            ('Tim', 'Ream', 'Defensa', 35, 'Fulham', 7),
            ('Antonee', 'Robinson', 'Defensa', 25, 'Fulham', 7),
            ('Joe', 'Scally', 'Defensa', 19, 'Borussia Monchenglachbach', 7),
            ('DeAndre', 'Yedlin', 'Defensa', 29, 'Inter Miami CF', 7),
            ('Walker', 'Zimmerman', 'Defensa', 29, 'Nashville SC', 7),
            ('Brenden', 'Aaronson', 'Mediocampista', 22, 'Leeds United', 7),
            ('Kellyn', 'Acosta', 'Mediocampista', 27, 'LAFC', 7),
            ('Tyler', 'Adams', 'Mediocampista', 23, 'Leeds United', 7),
            ('Luca', 'de la Torre', 'Mediocampista', 24, 'Celta de Vigo', 7),
            ('Weston', 'McKennie', 'Mediocampista', 24, 'Juventus', 7),
            ('Yunus', 'Musah', 'Mediocampista', 19, 'Valencia', 7),
            ('Cristian', 'Roldan', 'Mediocampista', 27, 'Seattle Sounders', 7),
            ('Jesús', 'Ferreira', 'Delantero', 21, 'FC Dallas', 7),
            ('Jordan', 'Morris', 'Delantero', 28, 'Seattle Sounders', 7),
            ('Christian', 'Pulisic', 'Delantero', 24, 'Chelsea', 7),
            ('Gio', 'Reyna', 'Delantero', 20, 'Borussia Dortmund', 7),
            ('Josh', 'Sargent', 'Delantero', 22, 'Norwich City', 7),
            ('Tim', 'Weah', 'Delantero', 22, 'Lille', 7),
            ('Haji', 'Wright', 'Delantero', 24, 'Antalyaspor', 7),
            ('Wayne', 'Hannessey', 'Portero', 35, 'Nottingham Forest', 8),
            ('Dany', 'Ward', 'Portero', 29, 'Leicester City', 8),
            ('Adam', 'Davies', 'Portero', 30, 'Sheffield United', 8),
            ('Ben', 'Davies', 'Defensa', 29, 'Tottenham', 8),
            ('Ben', 'Cabango', 'Defensa', 22, 'Swansea', 8),
            ('Tom', 'Lockyer', 'Defensa', 27, 'Luton Town', 8),
            ('Joe', 'Rodon', 'Defensa', 25, 'Rennes', 8),
            ('Chris', 'Mepham', 'Defensa', 25, 'Bournemoutht', 8),
            ('Ethan', 'Ampadu', 'Defensa', 22, 'Spezia', 8),
            ('Chris', 'Gunter', 'Defensa', 33, 'Wimbledon', 8),
            ('Neco', 'Williams', 'Defensa', 21, 'Nottingham Forest', 8),
            ('Connor', 'Roberts', 'Defensa', 27, 'Burnley', 8),
            ('Joe', 'Allen', 'Mediocampista', 32, 'Swansea', 8),
            ('Matt', 'Smith', 'Mediocampista', 22, 'MK Dons', 8),
            ('Dylan', 'Levitt', 'Mediocampista', 22, 'Dundee United', 8),
            ('Joe', 'Morrell', 'Mediocampista', 25, 'Porstmouth', 8),
            ('Jonny', 'Williams', 'Mediocampista', 29, 'Swindon Town', 8),
            ('Aaron', 'Ramsey', 'Mediocampista', 31, 'Niza', 8),
            ('Harry', 'Wilson', 'Mediocampista', 25, 'Fulham', 8),
            ('Rubin', 'Colwill', 'Delantero', 20, 'Cardiff City', 8),
            ('Sorba', 'Thomas', 'Delantero', 23, 'Huddersfield', 8),
            ('Gareth', 'Bale', 'Delantero', 33, 'Los Angeles FC', 8),
            ('Kieffer', 'Moore', 'Delantero', 30, 'Bournemoutht', 8),
            ('Mark', 'Harris', 'Delantero', 23, 'Cardiff City', 8),
            ('Brennan', 'Johnson', 'Delantero', 21, 'Nottingham Forest', 8),
            ('Dan', 'James', 'Delantero', 25, 'Leeds', 8),
            ('Emiliano', 'Martínez', 'Portero', 30, 'Aston Villa', 9),
            ('Gerónimo', 'Rulli', 'Portero', 30, 'Villareal', 9),
            ('Franco', 'Armani', 'Portero', 36, 'River Plate', 9),
            ('Gonzalo', 'Montiel', 'Defensa', 25, 'Sevilla', 9),
            ('Nicolás', 'Otamenti', 'Defensa', 34, 'Benfica', 9),
            ('Nahuel', 'Molina', 'Defensa', 24, 'Atlético de Madrid', 9),
            ('Cristian', 'Romero', 'Defensa', 24, 'Tottenham', 9),
            ('Germán', 'Pezzella', 'Defensa', 31, 'Betis', 9),
            ('Lisandro', 'Martínez', 'Defensa', 24, 'Manchester United', 9),
            ('Marcos', 'Acuña', 'Defensa', 31, 'Sevilla', 9),
            ('Nicolás', 'Tagliafico', 'Defensa', 30, 'Lyon', 9),
            ('Juan', 'Foyth', 'Defensa', 24, 'Villareal', 9),
            ('Leandro', 'Paredes', 'Mediocampista', 28, 'Juventus', 9),
            ('Guido', 'Rodriguez', 'Mediocampista', 28, 'Betis', 9),
            ('Rodrigo', 'De Paul', 'Mediocampista', 28, 'Atlético de Madrid', 9),
            ('Exequiel', 'Palacios', 'Mediocampista', 24, 'Bayer Leverkusen', 9),
            ('Alexis', 'MacAllister', 'Mediocampista', 23, 'Brighton', 9),
            ('Enzo', 'Fernández', 'Mediocampista', 21, 'Benfica', 9),
            ('Ángel', 'Di María', 'Mediocampista', 34, 'Juventus', 9),
            ('Alejandro', 'Gómez', 'Mediocampista', 34, 'Sevilla', 9),
            ('Nicolás', 'González', 'Delantero', 24, 'Fiorentina', 9),
            ('Julián', 'Álvarez', 'Delantero', 22, 'Manchester City', 9),
            ('Joaquín', 'Correa', 'Delantero', 28, 'Inter', 9),
            ('Lautaro', 'Martínez', 'Delantero', 25, 'Inter', 9),
            ('Lionel', 'Messi', 'Delantero', 35, 'Paris Saint-Germain', 9),
            ('Paulo', 'Dybala', 'Delantero', 29, 'Roma', 9),
            ('Mohammed', 'Al-Owais', 'Portero', 31, 'Al-Hilal', 10),
            ('Mohammed', 'Al Rubaei', 'Portero', 25, 'Al-Hilal', 10),
            ('Nawaf', 'Al-Aqidi', 'Portero', 22, 'Al-Nassr', 10),
            ('Yesser', 'Al-Shahrani', 'Defensa', 30, 'Al-Hilal', 10),
            ('Mohammed', 'Al-Breik', 'Defensa', 30, 'Al-Hilal', 10),
            ('Ali', 'Al-Bulaihi', 'Defensa', 32, 'Al-Hilal', 10),
            ('Sultan', 'Al-Ghanam', 'Defensa', 28, 'Al-Nassr', 10),
            ('Saud', 'Abdulhamid', 'Defensa', 23, 'Al-Hilal', 10),
            ('Abdulelah', 'Al-Amri', 'Defensa', 25, 'Al-Shabaq', 10),
            ('Hassan', 'Tambakti', 'Defensa', 23, 'Al-Nassr', 10),
            ('Abdullah', 'Madu', 'Defensa', 29, 'Al-Nassr', 10),
            ('Salem', 'Al-Dawsari', 'Mediocampista', 23, 'Al-Hilal', 10),
            ('Salman', 'Al-Faraj', 'Mediocampista', 33, 'Al-Hilal', 10),
            ('Abdullah', 'Otayf', 'Mediocampista', 30, 'Al-Hilal', 10),
            ('Hattan', 'Bahebri', 'Mediocampista', 30, 'Al-Shabaq', 10),
            ('Mohamed', 'Kanno', 'Mediocampista', 28, 'Al-Hilal', 10),
            ('Abdulellah', 'Al-Malki', 'Mediocampista', 28, 'Al-Hilal', 10),
            ('Sami', 'Al-Najei', 'Mediocampista', 25, 'Al-Nassr', 10),
            ('Ali', 'Al-Hassan', 'Mediocampista', 25, 'Al-Nassr', 10),
            ('Nesser', 'Al-Dawsari', 'Mediocampista', 31, 'Al-Hilal', 10),
            ('Riyadh', 'Sharahili', 'Mediocampista', 29, 'Abha', 10),
            ('Abdulrahman', 'Al-About', 'Mediocampista', 27, 'Al-Ittihad', 10),
            ('Firas', 'Al-Buraikan', 'Delantero', 22, 'Al-Fateh', 10),
            ('Newaf', 'Al-Abed', 'Delantero', 32, 'Al-Shabaq', 10),
            ('Saleh', 'Al-Shehri', 'Delantero', 29, 'Al-Hilal', 10),
            ('Haitham', 'Asiri', 'Delantero', 21, 'Al-Hilal', 10),
            ('Guillermo', 'Ochoa', 'Portero', 37, 'América', 11),
            ('Alfredo', 'Talavera', 'Portero', 40, 'Juárez FC', 11),
            ('Rodolfo', 'Cota', 'Portero', 35, 'León', 11),
            ('Kevin', 'Álvarez', 'Defensa', 23, 'Pachuca', 11),
            ('Néstor', 'Araujo', 'Defensa', 31, 'América', 11),
            ('Jesús', 'Gallardo', 'Defensa', 28, 'Monterrey', 11),
            ('Héctor', 'Moreno', 'Defensa', 34, 'Monterrey', 11),
            ('César', 'Montes', 'Defensa', 25, 'Monterrey', 11),
            ('Gerardo', 'Arteaga', 'Defensa', 24, 'Genk', 11),
            ('Jorge', 'Sánchez', 'Defensa', 24, 'Ajax', 11),
            ('Johan', 'Vázquez', 'Defensa', 24, 'Cremonese', 11),
            ('Luis', 'Romo', 'Mediocampista', 27, 'Monterrey', 11),
            ('Uriel', 'Antuna', 'Mediocampista', 25, 'Cruz Azul', 11),
            ('Luis', 'Chávez', 'Mediocampista', 26, 'Pachuca', 11),
            ('Carlos', 'Rodriguez', 'Mediocampista', 25, 'Cruz Azul', 11),
            ('Edson', 'Álvarez', 'Mediocampista', 25, 'Ajax', 11),
            ('Héctor', 'Herrera', 'Mediocampista', 32, 'Dynamo', 11),
            ('Erik', 'Gutiérrez', 'Mediocampista', 27, 'PSV', 11),
            ('Orbelín', 'Pineda', 'Mediocampista', 26, 'AEK Atenas', 11),
            ('Roberto', 'Alvarado', 'Mediocampista', 24, 'Chivas', 11),
            ('Andrés', 'Guardado', 'Mediocampista', 36, 'Betis', 11),
            ('Rogelio', 'Funes Mori', 'Delantero', 31, 'Monterrey', 11),
            ('Henry', 'Martín', 'Delantero', 30, 'América', 11),
            ('Raúl', 'Jiménez', 'Delantero', 31, 'Wolverhampton', 11),
            ('Hirving', 'Lozano', 'Delantero', 27, 'Napoli', 11),
            ('Alexis', 'Vega', 'Delantero', 24, 'Chivas', 11),
            ('Kamil', 'Grabara', 'Portero', 23, 'FC Copenhague', 12),
            ('Lukasz', 'Skorupski', 'Portero', 31, 'Bologna', 12),
            ('Wojciech', 'Szczesny', 'Portero', 32, 'Juventus', 12),
            ('Robert', 'Gummy', 'Defensa', 24, 'Augsburg', 12),
            ('Nicola ', 'Zalewski', 'Defensa', 20, 'Roma', 12),
            ('Jan', 'Bednarek', 'Defensa', 26, 'Aston Villa', 12),
            ('Bartosz', 'Bereszynski', 'Defensa', 30, 'Sampdoria', 12),
            ('Kamil', 'Glik', 'Defensa', 34, 'Benevento', 12),
            ('Matty', 'Cash', 'Defensa', 25, 'Aston Villa', 12),
            ('Mateusz', 'Wieteska', 'Defensa', 25, 'Clermont', 12),
            ('Jakub', 'Kiwior', 'Defensa', 22, 'Spezia', 12),
            ('Artur', 'Jedrzejczyk', 'Defensa', 35, 'Legia Warsaw', 12),
            ('Krystian', 'Bielik', 'Mediocampista', 24, 'Birmingham', 12),
            ('Przemyslaw', 'Frankowski', 'Mediocampista', 27, 'Lens', 12),
            ('Kamil', 'Grosicki', 'Mediocampista', 34, 'Pogon Szczecin', 12),
            ('Jakub', 'Kaminski', 'Mediocampista', 20, 'Wolfsburg', 12),
            ('Grzegorz', 'Krychowiak', 'Mediocampista', 32, 'Al Shabab', 12),
            ('Michal', 'Skóras', 'Mediocampista', 22, 'Lech Poznan', 12),
            ('Damian', 'Szymanski', 'Mediocampista', 27, 'AEK Athens', 12),
            ('Sebastian', 'Szymanski', 'Mediocampista', 23, 'Feyenoord', 12),
            ('Piotr', 'Zielinski', 'Mediocampista', 28, 'Napoli', 12),
            ('Szymon', 'Zurkowski', 'Mediocampista', 25, 'Fiorentina', 12),
            ('Robert', 'Lewandowski', 'Delantero', 34, 'Barcelona', 12),
            ('Arkadiusz', 'Milik', 'Delantero', 28, 'Juventus', 12),
            ('Krzystof', 'Piatek', 'Delantero', 27, 'Salernitana', 12),
            ('Karol', 'Swiderski', 'Delantero', 25, 'Charlotte', 12),
            ('Hugo', 'Lloris', 'Portero', 35, 'Tottenham ', 13),
            ('Steve', 'Mandanda', 'Portero', 24, 'Stade Rennois', 13),
            ('Alphonse', 'Aréola', 'Portero', 29, 'West Ham ', 13),
            ('Raphael', 'Varane', 'Defensor', 26, 'Manchester United ', 13),
            ('Jules', 'Koundé', 'Defensor', 25, 'Barcelona ', 13),
            ('Theo', 'Hernández', 'Defensor', 29, 'Milan ', 13),
            ('Dayot', 'Upamecano', 'Defensor', 24, 'Bayern Múnich ', 13),
            ('Ibrahima', 'Konaté', 'Defensor', 25, 'Liverpool ', 13),
            ('Axel', 'Disasi', 'Defensor', 24, 'Mónaco', 13),
            ('William', 'Saliba', 'Defensor', 26, 'Arsenal (Inglaterra)', 13),
            ('Benjamin', 'Pavard', 'Defensor', 25, 'Bayern Múnich (Alemania)', 13),
            ('Lucas', 'Hernández', 'Defensor', 23, 'Bayern Múnich (Alemania)', 13),
            ('Eduardo', 'Camavinga', 'Volante', 23, 'Real Madrid (España)', 13),
            ('Aurélien', 'Tchouaméni', 'Volante', 22, 'Real Madrid (España)', 13),
            ('Kingsley', 'Coman', 'Volante', 23, 'Bayern Múnich (Alemania)', 13),
            ('Adrien', 'Rabiot', 'Volante', 27, 'Juventus (Italia)', 13),
            ('Youssouf', 'Fofana', 'Volante', 29, 'Mónaco', 13),
            ('Mattéo', 'Guendouzi', 'Volante', 26, 'Marsella', 13),
            ('Jordan', 'Veretout', 'Volante', 31, 'Marsella', 13),
            ('Kylian', 'Mbappé', 'Delantero', 36, 'PSG', 13),
            ('Karim', 'Benzema', 'Delantero', 23, 'Real Madrid (España)', 13),
            ('Antoine', 'Griezmann', 'Delantero', 25, 'Atlético de Madrid (España)', 13),
            ('Ousmane', 'Dembélé', 'Delantero', 23, 'Barcelona (España)', 13),
            ('Olivier', 'Giroud', 'Delantero', 34, 'Milan (Italia)', 13),
            ('Marcus', 'Thuram', 'Delantero', 26, 'Borussia Monchengladbach ', 13),
            ('Randal', 'Kolo Muani', 'Delantero', 25, 'Eintracht Frankfurt ', 13),
            ('Mathew', 'Ryan', 'Portero', 30, 'FC Copenhagen (Dinamarca)', 14),
            ('Andrew', 'Redmayne', 'Portero', 33, 'Sydney FC', 14),
            ('Danny', 'Vukovic', 'Portero', 37, 'Central Coast Mariners', 14),
            ('Aziz', 'Behich', 'Defensor', 28, 'Dundee United (Escocia)', 14),
            ('Milos', 'Degenek', 'Defensor', 23, 'Columbus Crew (Estados Unidos)', 14),
            ('Thomas', 'Deng', 'Defensor', 24, 'Aibirex Niigata (Japón)', 14),
            ('Joel', 'King', 'Defensor', 26, 'Odense Boldklub (Dinamarca)', 14),
            ('Nathaniel', 'Atkinson', 'Defensor', 30, 'Hearts (Escocia)', 14),
            ('Fran', 'Karacic', 'Defensor', 32, 'Brescia (Italia)', 14),
            ('Harry', 'Souttar', 'Defensor', 24, 'Stoke City (inglaterra)', 14),
            ('Kye', 'Rowles', 'Defensor', 25, 'Hearts (Escocia)', 14),
            ('Craig', 'Goodwin', 'Defensor', 22, 'Adelaide United', 14),
            ('Aaron', 'Mooy', 'Volante', 26, 'Celtic (Escocia)', 14),
            ('Jackson', 'Irvine', 'Volante', 32, 'St. Pauli (Alemania)', 14),
            ('Ajdin', 'Hrustic', 'Volante', 24, 'Hellas Verona (Italia)', 14),
            ('Bailey', 'Wright', 'Volante', 24, 'Sunderland (Inglaterra)', 14),
            ('Cameron', 'Devlin', 'Volante', 29, 'Hearts (Escocia)', 14),
            ('Riley', 'McGree', 'Volante', 24, 'Middlesbrough (Inglaterra)', 14),
            ('Keanu', 'Baccus', 'Volante', 29, 'St. Mirren (Escocia)', 14),
            ('Awer', 'Mabil ', 'Delantero', 31, 'Cádiz (España)', 14),
            ('Mathew', 'Leckie', 'Delantero', 29, 'Melbourne City', 14),
            ('Martin', 'Boyle', 'Delantero', 27, 'Hibernian (Escocia)', 14),
            ('James', 'Maclaren', 'Delantero', 31, 'Melbourne City', 14),
            ('Jason', 'Cummings', 'Delantero', 18, 'Central Coast Mariners', 14),
            ('Mitchell', 'Duke', 'Delantero', 30, 'Fagiano Okayama (Japón)', 14),
            ('Garang', 'Kuol', 'Delantero', 27, 'Central Coast Mariners', 14),
            ('Kasper', 'Schmeichel', 'Portero', 36, 'Niza (Francia)', 15),
            ('Frederik', 'Ronnow', 'Portero', 30, 'Unión Berlín (Alemania)', 15),
            ('Oliver', 'Christensen', 'Portero', 23, 'Hertha Berlín (Alemania)', 15),
            ('Simon', 'Kjaer', 'Defensor', 33, 'Milan (Italia)', 15),
            ('Andreas', 'Christensen', 'Defensor', 26, 'Barcelona (España)', 15),
            ('Jens', 'Stryger', 'Defensor', 31, 'Trabzonspor (Turquía)', 15),
            ('Daniel', 'Wass', 'Defensor', 33, 'Brondby', 15),
            ('Joakim', 'Maehle', 'Defensor', 25, 'Atalanta (Italia)', 15),
            ('Joachim', 'Andersen', 'Defensor', 26, 'Crystal Palace (Inglaterra)', 15),
            ('Rasmus', 'Kristensen', 'Defensor', 25, 'Leeds (Inglaterra)', 15),
            ('Victor', 'Nelsson', 'Defensor', 24, 'Galatasaray (Turquía)', 15),
            ('Alexander', 'Bah', 'Defensor', 24, 'Bénfica (Portugal)', 15),
            ('Christian', 'Eriksen', 'Volante', 30, 'Manchester United (Inglaterra)', 15),
            ('Thomas', 'Delaney', 'Volante', 31, 'Sevilla (España)', 15),
            ('Pierre-Emile', 'Hojbjerg', 'Volante', 27, 'Tottenham Hotspur (Inglaterra)', 15),
            ('Mathias', 'Jensen', 'Volante', 26, 'Brentford (Inglaterra)', 15),
            ('Christian', 'Norgaard', 'Volante', 28, 'Brentford (Inglaterra)', 15),
            ('Yussuf', 'Poulsen', 'Delantero', 26, 'RB Leipzig (Alemania)', 15),
            ('Martin', 'Braithwaite', 'Delantero', 22, 'Espanyol (España)', 15),
            ('Andreas', 'Cornelius', 'Delantero', 28, 'Copenhague', 15),
            ('Kasper', 'Dolberg', 'Delantero', 31, 'Sevilla (España)', 15),
            ('Andreas', 'Skov', 'Delantero', 29, 'Brujas (Bélgica)', 15),
            ('Mikkel', 'Damsgaard', 'Delantero', 25, 'Brentford (Inglaterra)', 15),
            ('Jonas', 'Wind', 'Delantero', 22, 'Wolfsburgo (Alemania)', 15),
            ('Robert', 'Skov', 'Delantero', 22, 'Hoffenheim (Alemania)', 15),
            ('Jesper', 'Lindstrom', 'Delantero', 23, 'Eintracht Frankfurt (Alemania)', 15),
            ('Aymen', 'Dahmen', 'Arquero', 38, 'CS Sfaxien', 16),
            ('Mouez', 'Hasen', 'Arquero', 25, 'Club Africain', 16),
            ('Balbouli', 'Armey', 'Arquero', 27, 'Etoile du Sahel', 16),
            ('Bechir', 'Ben', 'Arquero', 27, 'US Monastir', 16),
            ('Mohamed', 'Drager', 'Defensor', 32, 'Luzern (Suiza)', 16),
            ('Wajdi', 'Kechrida', 'Defensor', 24, 'Atromitos (Grecia)', 16),
            ('Bilel', 'Ifa', 'Defensor', 29, 'Kuwait SC (Kuwait)', 16),
            ('Montassar', 'Talbi', 'Defensor', 27, 'Lorient (Francia)', 16),
            ('Dylan', 'Bronn', 'Defensor', 27, 'Salernitana (Italia)', 16),
            ('Yassine', 'Meriah', 'Defensor', 32, 'ES Tunis', 16),
            ('Nader', 'Ghandri', 'Defensor', 26, 'Club Africain', 16),
            ('Ali', 'Maaloul', 'Defensor', 27, 'Al Ahly (Egipto)', 16),
            ('Ali', 'Abdi', 'Defensor', 28, 'Caen (Francia)', 16),
            ('Ellyes', 'Skhiri', 'Mediocampista', 19, 'Koln (Alemania)', 16),
            ('Aissa', 'Laidouni', 'Mediocampista', 30, 'Ferencvaros (Hungría)', 16),
            ('Ferjani', 'Sassi', 'Mediocampista', 25, 'Al Duhail (Qatar)', 16),
            ('Ghailene', 'Chaalali', 'Mediocampista', 23, 'ES Tunis', 16),
            ('Mohamed', 'Ali', 'Mediocampista', 27, 'ES Tunis ', 16),
            ('Hannibal', 'Mejbri', 'Mediocampista', 28, 'Birmingham City (Inglaterra)', 16),
            ('Seifeddine', 'Jaziri', 'Delantero', 21, 'Zamalek (Egipto)', 16),
            ('Naim', 'Sliti', 'Delantero', 32, 'Al-Ettifaq (Arabia Saudita)', 16),
            ('Taha', 'Yassine', 'Delantero', 30, 'Kuwait SC (Kuwait)', 16),
            ('Anis', 'Ben', 'Delantero', 31, 'Brondby (Dinamarca)', 16),
            ('Issam', 'Jebali', 'Delantero', 30, 'OB (Dinamarca)', 16),
            ('Wahbi', 'Khazri', 'Delantero', 29, 'Montpellier (Francia)', 16),
            ('Youssef', 'Msakni', 'Delantero', 30, 'Al Arabi (Qatar)', 16),
            ('Unai', 'Simón', 'Portero', 25, 'Athletic Bilbao', 17),
            ('Robert', 'Sánchez', 'Portero', 25, 'Brighton (Inglaterra)', 17),
            ('David', 'Raya', 'Portero', 27, 'Brentford (Inglaterra)', 17),
            ('Jordi', 'Alba', 'Defensor', 33, 'Barcelona ', 17),
            ('Daniel', 'Carvajal', 'Defensor', 30, 'Real Madrid ', 17),
            ('Eric', 'García', 'Defensor', 21, 'Barcelona ', 17),
            ('Aymeric', 'Laporte', 'Defensor', 28, 'Manchester City (Inglaterra) ', 17),
            ('César', 'Azpilicueta', 'Defensor', 33, 'Chelsea (Inglaterra) ', 17),
            ('Pau', 'Torres', 'Defensor', 25, 'Villarreal ', 17),
            ('Alejandro', 'Balde', 'Defensor', 19, 'Barcelona', 17),
            ('Hugo', 'Guillamón', 'Defensor', 22, 'Valencia ', 17),
            ('Pedri', '', 'Mediocampista', 19, 'Barcelona ', 17),
            ('Gavi', '', 'Mediocampista', 18, 'Barcelona ', 17),
            ('Sergio', 'Busquets', 'Mediocampista', 34, 'Barcelona ', 17),
            ('Rodri', '', 'Mediocampista', 26, 'Manchester City (Inglaterra)', 17),
            ('Marcos', 'Llorente', 'Mediocampista', 27, 'Atlético de Madrid ', 17),
            ('Koke', '', 'Mediocampista', 30, 'Atlético de Madrid ', 17),
            ('Carlos', 'Soler', 'Mediocampista', 25, 'PSG (Francia) ', 17),
            ('Nico', 'Williams', 'Delantero ', 20, 'Athletic Bilbao ', 17),
            ('Yéremy', 'Pino', 'Delantero', 20, 'Villarreal ', 17),
            ('Ansu', 'Fati', 'Delantero', 20, 'Barcelona ', 17),
            ('Ferran', 'Torres', 'Delantero', 22, 'Barcelona ', 17),
            ('Marco', 'Asensio', 'Delantero', 26, 'Real Madrid ', 17),
            ('Álvaro', 'Morata', 'Delantero', 30, 'Atlético de Madrid ', 17),
            ('Dani', 'Olmo', 'Delantero', 24, 'RB Leipzig (Alemania) ', 17),
            ('Pablo', 'Sarabia', 'Delantero', 30, 'PSG (Francia) ', 17),
            ('Keylor', 'Navas', 'Portero', 35, 'Paris Saint-Germain (Francia)', 18),
            ('Esteban', 'Alvarado', 'Portero', 33, 'Herediano', 18),
            ('Patrick', 'Sequeira', 'Portero', 23, 'Lugo (España)', 18),
            ('Francisco', 'Calvo', 'Defensor', 30, 'Konyaspor (Turquía)', 18),
            ('Juan', 'Pablo', 'Defensor', 27, 'Millonarios (Colombia)', 18),
            ('Kendall', 'Waston', 'Defensor', 34, 'Saprissa', 18),
            ('Óscar', 'Duarte', 'Defensor', 33, 'Al-Wehda (Arabia Saudita)', 18),
            ('Daniel', 'Chacón', 'Defensor', 21, 'Colorado Rapids (Estados Unidos)', 18),
            ('Keysher', 'Fuller', 'Defensor', 28, 'Herediano', 18),
            ('Carlos', 'Martínez', 'Defensor', 23, 'San Carlos', 18),
            ('Bryan', 'Oviedo', 'Defensor', 32, 'Real Salt Lake (Estados Unidos)', 18),
            ('Ronald', 'Matarrita', 'Defensor', 28, 'Cincinnati (Estados Unidos)', 18),
            ('Yeltsin', 'Tejeda', 'Volante', 30, 'Herediano', 18),
            ('Celso', 'Borges', 'Volante', 34, 'Alajuelense', 18),
            ('Youstin', 'Salas', 'Volante', 26, 'Saprissa', 18),
            ('Roan', 'Wilson', 'Volante', 20, 'Municipal Grecia', 18),
            ('Gerson', 'Torres', 'Volante', 25, 'Herediano', 18),
            ('Douglas', 'López', 'Volante', 24, 'Herediano', 18),
            ('Jewison', 'Bennette', 'Volante', 18, 'Sunderland (Inglaterra)', 18),
            ('Álvaro', 'Zamora', 'Volante', 20, 'Saprissa', 18),
            ('Anthony', 'Hernández', 'Volante', 22, 'Puntarenas FC', 18),
            ('Brandon', 'Aguilera', 'Volante', 19, 'Nottingham Forest (Inglaterra)', 18),
            ('Bryan', 'Ruiz', 'Volante', 37, 'Alajuelense', 18),
            ('Joel', 'Campbell', 'Delantero', 30, 'León (México)', 18),
            ('Anthony', 'Contreras', 'Delantero', 20, 'Herediano', 18),
            ('Johan', 'Venegas', 'Delantero', 33, 'Alajuelense', 18),
            ('Manuel', 'Neuer', 'Portero', 36, 'Bayern Múnich', 19),
            ('Marc-Andre', 'Ter', 'Portero', 32, 'Barcelona (España)', 19),
            ('Kevin', 'Trapp', 'Portero', 30, 'Eintracht Frankfurt', 19),
            ('Armel', 'Bella-Kotchap', 'Defensor', 29, 'Southampton (Inglaterra)', 19),
            ('Matthias', 'Ginter', 'Defensor', 24, 'Friburgo', 19),
            ('Cristian', 'Gunter', 'Defensor', 28, 'Friburgo', 19),
            ('Thilo', 'Kehrer', 'Defensor', 26, 'West Ham (Inglaterra)', 19),
            ('Lukas', 'Klostermann', 'Defensor', 27, 'RB Leipzig', 19),
            ('David', 'Raum', 'Defensor', 26, 'RB Leipzig', 19),
            ('Antonio', 'Rudiger', 'Defensor', 29, 'Real Madrid (España)', 19),
            ('Nico', 'Schlotterback', 'Defensor', 22, 'Borussia Dortmund', 19),
            ('Niklas', 'Sule', 'Defensor', 20, 'Borussia Dortmund', 19),
            ('Mario', 'Gotze', 'Mediocampista', 27, 'Eintracht Frankfurt', 19),
            ('Julian', 'Brandt', 'Mediocampista', 23, 'Borussia Dortmund', 19),
            ('Jamal', 'Musiala', 'Mediocampista', 27, 'Bayern Múnich', 19),
            ('Leon', 'Goretzka', 'Mediocampista', 30, 'Bayern Múnich', 19),
            ('Ilkay', 'Gundogan', 'Mediocampista', 19, 'Manchester City (Inglaterra)', 19),
            ('Kai', 'Havertz', 'Mediocampista', 26, 'Chelsea (Inglaterra)', 19),
            ('Jonas', 'Hofmann', 'Mediocampista', 30, 'Borussia Monchengladbach', 19),
            ('Joshua', 'Kimmich', 'Mediocampista', 32, 'Bayern Múnich', 19),
            ('Youssoufa', 'Moukoko', 'Delantero', 29, 'Borussia Dortmund', 19),
            ('Thomas', 'Muller', 'Delantero', 27, 'Bayern Múnich', 19),
            ('Leroy', 'Sané', 'Delantero', 33, 'Bayern Múnich', 19),
            ('Niclas', 'Fullkrug', 'Delantero', 26, 'Werder Bremen', 19),
            ('Serge', 'Gnabry', 'Delantero', 20, 'Bayern Múnich', 19),
            ('Karim', 'Adeyemi', 'Delantero', 17, 'Borussia Dortmund', 19),
            ('Eiji', 'Kawashima', 'Portero', 39, 'Estrasburgo (Francia)', 20),
            ('Shuichi', 'Gonda', 'Portero', 33, 'Shimizu E-pulse', 20),
            ('Daniel', 'Schmidt', 'Portero', 30, 'Sint-Truiden (Bélgica)', 20),
            ('Yuto', 'Nagatomo', 'Defensor', 36, 'FC Tokyo', 20),
            ('Maya', 'Yoshida', 'Defensor', 34, 'Schalke 04 (Alemania)', 20),
            ('Hiroki', 'Sakai', 'Defensor', 23, 'Urawa Reds', 20),
            ('Shogo', 'Taniguchi', 'Defensor', 31, 'Kawasaki Frontale', 20),
            ('Miki', 'Yamane', 'Defensor', 28, 'Kawasaki Frontale', 20),
            ('Ko', 'Itakura', 'Defensor', 25, 'Borussia Monchengladbach (Alemania)', 20),
            ('Hiroki', 'Ito ', 'Defensor', 32, 'Stuttgart (Alemania)', 20),
            ('Takehiro', 'Tomiyasu', 'Defensor', 28, 'Arsenal (Inglaterra)', 20),
            ('Gaku', 'Shibasaki', 'Volante', 30, 'Leganés (España)', 20),
            ('Wataru', 'Endo ', 'Volante', 25, 'Stuttgart (Alemania)', 20),
            ('Junya', 'Ito', 'Volante', 29, 'Reims (Francia)', 20),
            ('Ritsu', 'Doan', 'Volante', 24, 'Friburgo (Alemania)', 20),
            ('Takumi', 'Minamino', 'Volante', 29, 'Mónaco (Francia)', 20),
            ('Hidemasa', 'Morita', 'Volante', 27, 'Sporting Lisboa (Portugal)', 20),
            ('Daichi', 'Kamada', 'Volante', 26, 'Eintracht Frankfurt (Alemania)', 20),
            ('Yuki', 'Soma', 'Volante', 25, 'Nagoya Grampus', 20),
            ('Kaoru', 'Mitoma', 'Volante', 25, 'Brighton (Inglaterra)', 20),
            ('Ao', 'Tanaka', 'Volante', 24, 'Fortuna Düsseldorf (Alemania)', 20),
            ('Takefusa', 'Kubo', 'Volante', 24, 'Real Sociedad (España)', 20),
            ('Daizen', 'Maeda', 'Delantero', 25, 'Celtic (Escocia)', 20),
            ('Takuma', 'Asano', 'Delantero', 27, 'Bochum (Alemania)', 20),
            ('Ayase', 'Ueda', 'Delantero', 24, 'Círculo de Brujas (Bélgica)', 20),
            ('Shuto', 'Machino', 'Delantero', 21, 'Shonan Bellmare', 20),
            ('Thibaut', 'Courtois', 'Portero', 30, 'Real Madrid', 21),
            ('Simon', 'Mignolet', 'Portero', 34, 'Brujas', 21),
            ('Koen', 'Casteels', 'Portero', 30, 'Wolfsburgo', 21),
            ('Toby', 'Alderweireld', 'Defensor', 33, 'Royal Antwerp', 21),
            ('Arthur', 'Theate', 'Defensor', 22, 'Stade Rennes', 21),
            ('Wout', 'Faes', 'Defensor', 24, 'Leicester City', 21),
            ('Jan', 'Vertonghen', 'Defensor', 35, 'Anderlecht', 21),
            ('Thomas', 'Meunier', 'Defensor', 31, 'Borussia Dortmund', 21),
            ('Timothy', 'Castagne', 'Defensor', 26, 'Leicester City', 21),
            ('Zeno', 'Debast', 'Defensor', 19, 'Anderlecht', 21),
            ('Kevin', 'de Bruyne', 'Mediocampista', 31, 'Manchester City', 21),
            ('Hans', 'Vanaken', 'Mediocampista', 30, 'Brujas', 21),
            ('Youri ', 'Tielemans', 'Mediocampista', 25, 'Leicester City', 21),
            ('Leander', 'Dendoncker', 'Mediocampista', 27, 'Aston Villa', 21),
            ('Amadou', 'Onana', 'Mediocampista', 21, 'Everton', 21),
            ('Yannick', 'Carrasco', 'Mediocampista', 29, 'Atlético de Madrid', 21),
            ('Axel', 'Witsel', 'Mediocampista', 33, 'Atlético de Madrid', 21),
            ('Charles ', 'de Ketelaere', 'Mediocampista', 21, 'Milan', 21),
            ('Thorgan', 'Hazard', 'Mediocampista', 29, 'Borussia Dortmund', 21),
            ('Leandro', 'Trossard', 'Delantero ', 27, 'Brighton', 21),
            ('Romelu ', 'Lukaku', 'Delantero', 29, 'Inter', 21),
            ('Michy', 'Batshuayi', 'Delantero', 29, 'Fenerbahce', 21),
            ('Dries', 'Mertens', 'Delantero', 35, 'Galatasaray', 21),
            ('Eden', 'Hazars', 'Delantero', 31, 'Real Madrid', 21),
            ('Lois', 'Openda', 'Delantero', 22, 'Lens', 21),
            ('Jeremy', 'Doku', 'Delantero', 20, 'Stade Rennes', 21),
            ('James', 'Pantemis', 'Portero', 25, 'CF Montreal', 22),
            ('Milan', 'Borjan', 'Portero', 35, 'Red Star Belgrado', 22),
            ('Dayne', 'St. Clair', 'Portero', 25, 'Minnesota United', 22),
            ('Samuel', 'Adekugbe', 'Defensor', 24, 'Hatayspor', 22),
            ('Joel', 'Waterman', 'Defensor', 26, 'CF Montreal', 22),
            ('Alistair', 'Johnston', 'Defensor', 24, 'CF Montreal', 22),
            ('Richie', 'Laryea', 'Defensor', 27, 'Toronto FC', 22),
            ('Kamal', 'Miller', 'Defensor', 25, 'CF Montreal', 22),
            ('Steven', 'Vitoria', 'Defensor', 35, 'GD Chaves', 22),
            ('Derek', 'Cornelius', 'Defensor', 24, 'Panetolikos', 22),
            ('Liam', 'Frase', 'Mediocampista', 24, 'KMSK Deinze', 22),
            ('Ismael', 'Koné', 'Mediocampista', 20, 'CF Montreal', 22),
            ('Mark Anthony', 'Kaye', 'Mediocampista', 27, 'Toronto FC', 22),
            ('David', 'Wotherspoon', 'Mediocampista', 32, 'St. Johnstone', 22),
            ('Jonathan', 'Osorio', 'Mediocampista', 30, 'Toronto FC', 22),
            ('Atiba', 'Hutchinson', 'Mediocampista', 39, 'Besitkas', 22),
            ('Stephen', 'Eustaquio', 'Mediocampista', 25, 'FC Porto', 22),
            ('Samuel', 'Piette', 'Mediocampista', 28, 'CF Montreal', 22),
            ('Liam', 'Millar', 'Delantero', 23, 'Basilea', 22),
            ('Lucas', 'Cavallini', 'Delantero', 29, 'Vancouver Whitecaps', 22),
            ('Ike', 'Ugbo', 'Delantero', 24, 'Troyes', 22),
            ('Tajon', 'Buchanan', 'Delantero', 23, 'Club Brugge', 22),
            ('Jonathan', 'David', 'Delantero', 22, 'Lille', 22),
            ('Cyle', 'Larin', 'Delantero', 27, 'Club Brugge', 22),
            ('Alphonso', 'Davies', 'Delantero', 22, 'Bayern Munich', 22),
            ('Junior', 'Hoilett', 'Delantero', 32, 'Reading FC', 22),
            ('Yassine', 'Bono', 'Portero', 31, 'Sevilla', 23),
            ('Munir', 'Mohamedi', 'Portero', 33, 'Al-Wehda', 23),
            ('Ahmed Reda', 'Tagnaouti', 'Portero', 26, 'Wydad', 23),
            ('Achraf', 'Hakimi', 'Defensor', 24, 'PSG', 23),
            ('Noussair', 'Mazraoui', 'Defensor', 25, 'Bayern Munich', 23),
            ('Romain', 'Saiss', 'Defensor', 32, 'Besitkas', 23),
            ('Nayef', 'Aguerd', 'Defensor', 26, 'West Ham', 23),
            ('Achraf', 'Dari', 'Defensor', 23, 'Brest', 23),
            ('Jawad', 'El-Yamiq', 'Defensor', 30, 'Valladolid', 23),
            ('Yahia', 'Attiat-Allal', 'Defensor', 27, 'Wydad', 23),
            ('Badr', 'Benoun', 'Defensor', 29, 'Qatar SC', 23),
            ('Sofyan', 'Amrabat', 'Mediocampista', 26, 'Fiorentina', 23),
            ('Selim', 'Amallah', 'Mediocampista', 26, 'Standard Lieja', 23),
            ('Abdelhamid', 'Sabiri', 'Mediocampista', 25, 'Sampdoria', 23),
            ('Azzedine', 'Ounahi', 'Mediocampista', 22, 'Angers', 23),
            ('Bilel', 'El Khanouss', 'Mediocampista', 18, 'Genk', 23),
            ('Yahya', 'Jabrane', 'Mediocampista', 31, 'Wydad', 23),
            ('Haim', 'Ziyech', 'Delantero', 29, 'Chelsea', 23),
            ('Youssef', 'En-Nesyri', 'Delantero', 25, 'Sevilla', 23),
            ('Sofiane', 'Boufal', 'Delantero', 29, 'Angers', 23),
            ('Zakaria', 'Aboukhlal', 'Delantero', 22, 'Toulouse', 23),
            ('Abde', 'Ezzalzouli', 'Delantero', 20, 'Osasuna', 23),
            ('Anass', 'Zaroury', 'Delantero', 22, 'Burnley', 23),
            ('Ilias', 'Chair', 'Delantero', 25, 'QPR', 23),
            ('Abderrazak', 'Hamdallah', 'Delantero', 31, 'Al-ittihad', 23),
            ('Walid', 'Cheddira', 'Delantero', 24, 'Bari', 23),
            ('Dominik', 'Livakovic', 'Portero', 27, 'Dinamo Zagreb', 24),
            ('Ivica', 'Ivusic', 'Portero', 27, 'Osijek', 24),
            ('Ivo', 'Grbic', 'Portero', 26, 'Atlético de Madrid', 24),
            ('Josip', 'Stanisic', 'Defensor', 22, 'Bayern Munich', 24),
            ('Borna', 'Barisic', 'Defensor', 30, 'Rangers', 24),
            ('Josip', 'Sutalo', 'Defensor', 22, 'Dinamo Zagreb', 24),
            ('Dejan', 'Lovren', 'Defensor', 33, 'Zenit St. Petersburg', 24),
            ('Borna', 'Sosa', 'Defensor', 24, 'Stuttgart', 24),
            ('Josko', 'Gvardiol', 'Defensor', 20, 'RB Leipzig', 24),
            ('Domagoj', 'Vida', 'Defensor', 33, 'AEK Atenas', 24),
            ('Josip', 'Juranovic', 'Defensor', 27, 'Celtic', 24),
            ('Martin', 'Erlic', 'Defensor', 24, 'Sassuolo', 24),
            ('Lovro', 'Majer', 'Mediocampista', 24, 'Rennes', 24),
            ('Mateo', 'Kovacic', 'Mediocampista', 28, 'Chelsea', 24),
            ('Luka', 'Modric', 'Mediocampista', 37, 'Real Madrid', 24),
            ('Marcelo', 'Brozovic', 'Mediocampista', 30, 'Inter', 24),
            ('Mario', 'Pasalic', 'Mediocampista', 27, 'Atalanta', 24),
            ('Nikola', 'Vlasic', 'Mediocampista', 25, 'Torino', 24),
            ('Luka', 'Sucic', 'Mediocampista', 20, 'RB Salzburgo', 24),
            ('Kristijan', 'Jakic', 'Mediocampista', 25, 'Eintracht Frankfurt', 24),
            ('Ivan', 'Perisic', 'Delantero', 33, 'Tottenham', 24),
            ('Andrej', 'Kramaric', 'Delantero', 31, 'Hoffenheim', 24),
            ('Marko', 'Livaja', 'Delantero', 29, 'Hajduk Split', 24),
            ('Bruno', 'Petkovic', 'Delantero', 28, 'Dinamo Zagreb', 24),
            ('Ante', 'Budimir', 'Delantero', 31, 'Osasuna', 24),
            ('Mislav', 'Orsic', 'Delantero', 29, 'Dinamo Zagreb', 24),
            ('Alisson', 'Becker', 'Portero', 30, 'Liverpool', 25),
            ('Weverton', 'da Silva', 'Portero', 34, 'SE Palmeiras', 25),
            ('Ederson', 'de Moraes', 'Portero', 29, 'Manchester City', 25),
            ('Danilo', 'da Silva', 'Defensor', 31, 'Juventus', 25),
            ('Thiago', 'da Silva', 'Defensor', 38, 'Chelsea', 25),
            ('Marquinhos', 'Correa', 'Defensor', 28, 'PSG', 25),
            ('Alex Sandro', 'Silva', 'Defensor', 31, 'Juventus', 25),
            ('Dani Alves', 'da Silva', 'Defensor', 39, 'Pumas', 25),
            ('Alex', 'Telles', 'Defensor', 29, 'Sevilla', 25),
            ('Eder', 'Militao', 'Defensor', 24, 'Real Madrid', 25),
            ('Bremer', 'Silva', 'Defensor', 25, 'Juventus', 25),
            ('Carlos', 'Casemiro', 'Mediocampista', 30, 'Manchester United', 25),
            ('Lucas', 'Coelho', 'Mediocampista', 25, 'West Ham', 25),
            ('Fred', 'Santos', 'Mediocampista', 29, 'Manchester United', 25),
            ('Favio', 'Tabares', 'Mediocampista', 29, 'Liverpool', 25),
            ('Bruno', 'Rodrigues', 'Mediocampista', 25, 'Newcastle United', 25),
            ('Everton', 'Ribeiro', 'Mediocampista', 33, 'CR Flamengo', 25),
            ('Richarlison', 'de Andrade', 'Delantero', 25, 'Tottenham', 25),
            ('Neymar', 'Santos', 'Delantero', 30, 'PSG', 25),
            ('Raphael', 'Belloli', 'Delantero', 26, 'FC Barcelona', 25),
            ('Antony', 'Dos Santos', 'Delantero', 22, 'Manchester United', 25),
            ('Gabriel', 'Jesus', 'Delantero', 25, 'Arsenal', 25),
            ('Vinicius', 'de Oliveira', 'Delantero', 22, 'Real Madrid', 25),
            ('Rodrygo', 'de Goes', 'Delantero', 21, 'Real Madrid', 25),
            ('Gabriel', 'Martinelli', 'Delantero', 21, 'Arsenal', 25),
            ('Pedro', 'Abreu', 'Delantero', 25, 'CR Flamengo', 25),
            ('Vanja', 'Milinkovic-Savic', 'Portero', 25, 'Torino', 26),
            ('Predrag', 'Rajkovic', 'Portero', 27, 'Mallorca', 26),
            ('Marko', 'Dmitrovic', 'Portero', 30, 'Sevilla', 26),
            ('Milos', 'Veljkovic', 'Defensor', 27, 'Werder Bremen', 26),
            ('Strahinja', 'Pavlovic', 'Defensor', 21, 'RB Salzburgo', 26),
            ('Strahinja', 'Erakovic', 'Defensor', 21, 'Estrella Roja', 26),
            ('Nikola', 'Milenkovic', 'Defensor', 25, 'Fiorentina', 26),
            ('Stefan', 'Mitrovic', 'Defensor', 32, 'Getafe', 26),
            ('Filip', 'Mladenovic', 'Defensor', 31, 'Legia Varsovia', 26),
            ('Srdjan', 'Babic', 'Defensor', 26, 'Almería', 26),
            ('Nemanja', 'Gudelj', 'Mediocampista', 31, 'Sevilla', 26),
            ('Sergej', 'Milinkovic-Savic', 'Mediocampista', 27, 'Lazio', 26),
            ('Sasa', 'Lukic', 'Mediocampista', 26, 'Torino', 26),
            ('Filip', 'Kostic', 'Mediocampista', 30, 'Juventus', 26),
            ('Uros', 'Racic', 'Mediocampista', 24, 'Sporting Braga', 26),
            ('Ivan', 'Ilic', 'Mediocampista', 21, 'Hellas Verona', 26),
            ('Andrija', 'Zivkovic', 'Mediocampista', 26, 'PAOK', 26),
            ('Darko', 'Lazovic', 'Mediocampista', 32, 'Hellas Verona', 26),
            ('Nemanja', 'Maksimovic', 'Mediocampista', 27, 'Getafe', 26),
            ('Marko', 'Grujic', 'Mediocampista', 26, 'Porto', 26),
            ('Aleksandar', 'Mitrovic', 'Delantero', 28, 'Fulham', 26),
            ('Filip', 'Djuricic', 'Delantero', 30, 'Sampdoria', 26),
            ('Nemanja', 'Radonjic', 'Delantero', 26, 'Torino', 26),
            ('Luka', 'Jovic', 'Delantero', 24, 'Fiorentina', 26),
            ('Dusan', 'Tadic', 'Delantero', 33, 'Ajax', 26),
            ('Dusan', 'Vlahovic', 'Delantero', 22, 'Juventus', 26),
            ('Yan', 'Sommer', 'Portero', 33, 'Borussia Monchengladbach', 27),
            ('Jonas', 'Omlin', 'Portero', 28, 'Montpellier', 27),
            ('Gregor', 'Kobel', 'Portero', 24, 'Borussia Dortmund', 27),
            ('Philipp', 'Kohn', 'Portero', 24, 'RB Salzburgo', 27),
            ('Ricardo ', 'Rodriguez', 'Defensor', 30, 'Torino', 27),
            ('Fabian', 'Schar', 'Defensor', 33, 'Newcastle United', 27),
            ('Manuel', 'Akanji', 'Defensor', 27, 'Manchester City', 27),
            ('Nico', 'Elvedi', 'Defensor', 26, 'Borussia Monchengladbach', 27),
            ('Silvan', 'Widmer', 'Defensor', 29, 'Mainz 05', 27),
            ('Eray', 'Comert', 'Defensor', 24, 'Valencia', 27),
            ('Xherdan', 'Shaqiri', 'Mediocampista', 31, 'Chicago Fire', 27),
            ('Granit', 'Xhaka', 'Mediocampista', 30, 'Arsenal', 27),
            ('Remo', 'Freuler', 'Mediocampista', 30, 'Notthingham Forest', 27),
            ('Denis', 'Zakaria', 'Mediocampista', 25, 'Chelsea', 27),
            ('Djibril', 'Sow', 'Mediocampista', 25, 'Eintracht Frankfurt', 27),
            ('Renato', 'Steffen', 'Mediocampista', 31, 'Lugano', 27),
            ('Fabian', 'Frei', 'Mediocampista', 20, 'Basilea', 27),
            ('Michel', 'Aebischer', 'Mediocampista', 25, 'Bolonia', 27),
            ('Ardon', 'Jashari', 'Mediocampista', 20, 'Luzern', 27),
            ('Edimilson', 'Fernandes', 'Mediocampista', 26, 'Mainz 05', 27),
            ('Fabian', 'Rieder', 'Mediocampista', 30, 'Young Boys', 27),
            ('Haris', 'Seferovic', 'Delantero', 30, 'Galatasaray', 27),
            ('Breel', 'Embolo', 'Delantero', 25, 'Monaco', 27),
            ('Ruben', 'Vargas', 'Delantero', 24, 'Augsburgo', 27),
            ('Noah', 'Okafor', 'Delantero', 22, 'RB Salzburgo', 27),
            ('Christian', 'Fassnacht', 'Delantero', 29, 'Young Boys', 27),
            ('André', 'Onana', 'Portero', 26, 'Inter', 28),
            ('Simon', 'Ngapandouetnbu', 'Portero', 21, 'Marsella', 28),
            ('Devis', 'Epassy', 'Portero', 29, 'Abha', 28),
            ('Jean-Charles', 'Castelleto', 'Defensor ', 27, 'Nantes', 28),
            ('Enzo', 'Ebosse', 'Defensor ', 23, 'Udinese', 28),
            ('Collins', 'Fai', 'Defensor ', 29, 'Al-Tai', 28),
            ('Nouhou', 'Tolo', 'Defensor ', 25, 'Seattle Sounders', 28),
            ('Olivier', 'Mbaizo', 'Defensor ', 25, 'Philadelphia Union', 28),
            ('Nicolas', 'Nkoulou', 'Defensor ', 32, 'Aris', 28),
            ('Christopher', 'Wooh', 'Defensor ', 11, 'Rennes', 28),
            ('Olivier', 'Ntcham', 'Mediocampista', 26, 'Swansea', 28),
            ('Gael', 'Ondoa', 'Mediocampista', 27, 'Hannover 96', 28),
            ('Martin', 'Hongla', 'Mediocampista', 24, 'Hellas Verona', 28),
            ('Pierre', 'Kunde', 'Mediocampista', 27, 'Olympiacos', 28),
            ('Samuel', 'Oum Gouet', 'Mediocampista', 19, 'Mechelen', 28),
            ('André-Frank', 'Zambo', 'Mediocampista', 27, 'Napoli', 28),
            ('Moumi', 'Ngamaleu', 'Mediocampista', 28, 'Young Boys', 28),
            ('Jerome', 'Ngom Mbekeli', 'Mediocampista', 24, 'Colombe Sportive', 28),
            ('Souaibou', 'Marou', 'Delantero', 30, 'Coton Sport', 28),
            ('Christian', 'Bassogog', 'Delantero', 27, 'Shanghai Shenhua', 28),
            ('Bryan', 'Mbeumo', 'Delantero', 23, 'Drentford', 28),
            ('Jean-Pierre', 'Nsame', 'Delantero', 29, 'Young Boys', 28),
            ('Georges-Kevin', 'Nkoudou', 'Delantero', 27, 'Besiktas', 28),
            ('Karl', 'Toko Ekambi', 'Delantero', 30, 'Lyon', 28),
            ('Vincent', 'Aboubakar', 'Delantero', 30, 'Al-Nassr', 28),
            ('Eric Maxim', 'Choupo-Moting', 'Delantero', 33, 'Bayern Munich', 28),
            ('Diogo', 'Costa', 'Portero', 23, 'Porto', 29),
            ('Rui', 'Patricio', 'Portero', 34, 'Roma', 29),
            ('José', 'Sá', 'Portero', 29, 'Wolverhampton', 29),
            ('Joao ', 'Cancelo', 'Defensor', 28, 'Manchester City', 29),
            ('Diogo ', 'Dalot', 'Defensor', 23, 'Manchester United', 29),
            ('Képler Laverán', 'Lima Ferreira', 'Defensor', 39, 'Porto', 29),
            ('Rúben ', 'Dias', 'Defensor', 25, 'Manchester City', 29),
            ('Danilo ', 'Pereira', 'Defensor', 31, 'Paris Saint-Germain', 29),
            ('António', 'Silva', 'Defensor', 19, 'Benfica', 29),
            ('Nuno', 'Mendes', 'Defensor', 20, 'Paris Saint-Germain', 29),
            ('Raphael ', 'Guerreiro', 'Defensor', 28, 'Borussia Dortmund', 29),
            ('William ', 'Carvalho', 'Mediocampista', 30, 'Betis', 29),
            ('Rúben ', 'Neves', 'Mediocampista', 25, 'Wolverhampton ', 29),
            ('João Maria', 'Palhinha ', 'Mediocampista', 27, 'Fulham ', 29),
            ('Bruno ', 'Fernandes', 'Mediocampista', 28, 'Manchester United', 29),
            ('Vítor ', 'Ferreira', 'Mediocampista', 22, 'Paris Saint-Germain', 29),
            ('Otávio ', 'da Silva', 'Mediocampista', 27, 'Porto', 29),
            ('Matheus ', 'Nunes', 'Mediocampista', 24, 'Wolverhampton', 29),
            ('Bernardo ', 'Silva', 'Mediocampista', 28, 'Manchester City', 29),
            ('Joao ', 'Mario', 'Mediocampista', 29, 'Benfica', 29),
            ('Cristiano ', 'Ronaldo', 'Delantero ', 37, 'Manchester United', 29),
            ('Joao ', 'Félix', 'Delantero ', 23, 'Atlético de Madrid', 29),
            ('Rafael ', 'Leao', 'Delantero ', 23, 'Milan ', 29),
            ('Ricardo ', 'Horta', 'Delantero ', 28, 'Braga', 29),
            ('André ', 'Silva', 'Delantero ', 27, 'Leipzig ', 29),
            ('Gonçalo', 'Ramos', 'Delantero ', 21, 'Benfica', 29),
            ('Fernando', 'Muslera', 'Portero', 36, 'Galatasaray', 30),
            ('Sergio', 'Rochet', 'Portero', 29, 'Nacional', 30),
            ('Sebastián', 'Sosa', 'Portero', 36, 'Independiente', 30),
            ('Ronald', 'Araujo', 'Defensor', 23, 'Barcelona', 30),
            ('José', 'Giménez', 'Defensor', 27, 'Atlético de Madrid', 30),
            ('Sebastián', 'Coates', 'Defensor', 32, 'Sporting', 30),
            ('Diego', 'Godín', 'Defensor', 36, 'Vélez', 30),
            ('Martín', 'Cáceres', 'Defensor', 35, 'LA Galaxy', 30),
            ('Guillermo ', 'Varela', 'Defensor', 29, 'Flamengo ', 30),
            ('José', 'Rodríguez', 'Defensor', 25, 'Nacional', 30),
            ('Mathias', 'Olivera', 'Defensor', 25, 'Napoli', 30),
            ('Matías ', 'Viña', 'Defensor', 25, 'Roma', 30),
            ('Lucas', 'Torreira', 'Mediocampista', 26, 'Galatasaray', 30),
            ('Manuel', 'Ugarte', 'Mediocampista', 21, 'Sporting', 30),
            ('Matías', 'Vecino', 'Mediocampista', 31, 'Lazio', 30),
            ('Rodrigo', 'Bentancur', 'Mediocampista', 25, 'Tottenham ', 30),
            ('Federico', 'Valverde', 'Mediocampista', 24, 'Real Madrid', 30),
            ('Facundo ', 'Pellistri', 'Mediocampista', 20, 'Manchester United', 30),
            ('Agustín', 'Canobbio', 'Mediocampista', 24, 'Athletico Paranaense', 30),
            ('Nicolás', 'De La Cruz', 'Mediocampista', 25, 'River Plate', 30),
            ('Giorgian', 'De Arrascaeta', 'Mediocampista', 28, 'Flamengo ', 30),
            ('Maximiliano', 'Gómez', 'Delantero', 26, 'Trabzonspor', 30),
            ('Facundo', 'Torres', 'Delantero', 22, 'Orlando City', 30),
            ('Luis', 'Suárez', 'Delantero', 35, 'Nacional', 30),
            ('Edinson ', 'Cavani', 'Delantero', 35, 'Valencia', 30),
            ('Darwin ', 'Núñez', 'Delantero', 23, 'Liverpool', 30),
            ('Kim ', 'Seung-gyu', 'Portero', 32, 'Al-Shabab', 31),
            ('Jo', 'Hyeon-woo', 'Portero', 31, 'Ulsan Hyundai', 31),
            ('Song', ' Bum-keun', 'Portero', 25, 'Jeonbuk Hyundai Motors', 31),
            ('Kim ', 'Young-gwon', 'Defensor', 32, 'Ulsan Hyundai', 31),
            ('Kim', 'Jin-su', 'Defensor', 30, 'Jeonbuk Hyundai Motors', 31),
            ('Hong', 'Chul', 'Defensor', 32, 'Daegu FC', 31),
            ('Kim ', 'Min-jae', 'Defensor', 26, 'Napoli', 31),
            ('Kwon', 'Kyung-won', 'Defensor', 30, 'Gamba Osaka', 31),
            ('Kim ', 'Moon-hwan', 'Defensor', 27, 'Jeonbuk Hyundai Motors', 31),
            ('Kim ', 'Tae-hwan', 'Defensor', 33, 'Ulsan Hyundai', 31),
            ('Cho', 'Yu-min', 'Defensor', 26, 'Daejon Hana Citizen', 31),
            ('Yoon', 'Jong-gyu', 'Defensor', 24, 'FC Seúl', 31),
            ('Son', 'Heung-min', 'Mediocampista', 30, 'Tottenham', 31),
            ('Jung', 'Woo-young', 'Mediocampista', 32, 'Al-Sadd', 31),
            ('Lee', 'Jae-sung', 'Mediocampista', 30, 'Mainz 05', 31),
            ('Hwang', 'Hee-chan', 'Mediocampista', 26, 'Wolverhampton ', 31),
            ('Kwon', 'Chang-hoon', 'Mediocampista', 28, 'Gimcheon Sangmu', 31),
            ('Hwang', 'In-beom', 'Mediocampista', 26, 'Olympiacos', 31),
            ('Na', 'Sang-ho', 'Mediocampista', 26, 'FC Seúl', 31),
            ('Son', 'Jun-ho', 'Mediocampista', 30, 'Shandong Taishan', 31),
            ('Paik ', 'Seung-ho', 'Mediocampista', 25, 'Jeonbuk Hyundai Motors', 31),
            ('Song', 'Min-kyu', 'Mediocampista', 23, 'Jeonbuk Hyundai Motors', 31),
            ('Jeong', 'Woo-yeong', 'Mediocampista', 23, 'Friburgo ', 31),
            ('Lee', 'Kang-in', 'Mediocampista', 21, 'Mallorca', 31),
            ('Hwang', 'Ui-jo', 'Delantero', 30, 'Olympiacos', 31),
            ('Cho', 'Gue-sung', 'Delantero', 24, 'Jeonbuk Hyundai Motors', 31),
            ('Lawrence ', 'Ati Zigi', 'Portero', 25, 'St. Gallen', 32),
            ('Abdul ', 'Manaf Nurudeen', 'Portero', 23, 'Eupen', 32),
            ('Ibrahim', 'Danlad', 'Portero', 19, 'Berekum Chelsea', 32),
            ('Tariq', 'Lamptey', 'Defensor', 22, 'Brighton', 32),
            ('Alidu', 'Seidu', 'Defensor', 22, 'Clermont Foot', 32),
            ('Alexander', 'Djiku', 'Defensor', 28, 'Estrasburgo', 32),
            ('Gideon', ' Mensah', 'Defensor', 24, 'Auxerre ', 32),
            ('Dennis', 'Odoi', 'Defensor', 34, 'Brugge', 32),
            ('Daniel', 'Amartey', 'Defensor', 27, 'Leicester City', 32),
            ('Mohammed ', 'Salisu', 'Defensor', 23, 'Southampton ', 32),
            ('Joseph ', 'Aidoo', 'Defensor', 27, 'Celta', 32),
            ('Baba', 'Abdul Rahman', 'Defensor', 28, 'Reading ', 32),
            ('Andre', 'Ayew', 'Mediocampista', 32, 'Al Sadd', 32),
            ('Mohammed', 'Kudus', 'Mediocampista', 22, 'Ajax', 32),
            ('Abdul', 'Issahaku', 'Mediocampista', 18, 'Sporting CP', 32),
            ('Thomas', 'Partey', 'Mediocampista', 29, 'Arsenal', 32),
            ('Antoine', 'Semenyo', 'Mediocampista', 22, 'Bristol City', 32),
            ('Elisha', 'Owusu', 'Mediocampista', 25, 'Gent', 32),
            ('Sowah', 'Kamal', 'Mediocampista', 22, 'Brugge', 32),
            ('Kamaldeen', 'Sulemana', 'Mediocampista', 20, 'Rennes ', 32),
            ('Daniel', 'Kyereh', 'Delantero', 26, 'Freiburg ', 32),
            ('Abdul ', 'Salis Samed', 'Delantero', 22, 'Lens', 32),
            ('Osman ', 'Bukari', 'Delantero', 23, 'Red Star Belgrade', 32),
            ('Daniel', 'Barnieh', 'Delantero', 21, 'Hearts of Oak', 32),
            ('Iñaki', 'Williams', 'Delantero', 28, 'Athletic Club', 32),
            ('Jordan', 'Ayew', 'Delantero', 31, 'Crystal Palace', 32);
        ");
    }
}
